require "active_record"
require "active_record_nested_attribute_id_extension/one_to_one"
require "active_record_nested_attribute_id_extension/collection"
require "active_record_nested_attribute_id_extension/railtie"
require "active_record_nested_attribute_id_extension/version"

module ActiveRecordNestedAttributeIdExtension
end
